# Add vehicle
POST http://localhost:9090/graphql
Content-Type: application/json

{
  "query": "mutation addVehicle($vehicle: VehicleInput!){  addVehicle(vehicle: $vehicle) {      id    modelCode    color     someDerivedField    brand {          country        name  managerName    } } }",
  "variables": {
  	"vehicle": {
  		"brandId": "1",
  		"modelCode": "A4",
    	"color": "red"
  	}
  }
}


###

# Add vehicle
POST http://localhost:9090/graphql
Content-Type: application/json

{
  "query": "mutation addVehicle($vehicle: VehicleInput!){  addVehicle(vehicle: $vehicle) {      id    modelCode    color     someDerivedField    brand {          country        name  managerName    } } }",
  "variables": {
  	"vehicle": {
  		"brandId": "2",
  		"modelCode": "E63",
    	"color": "blue"
  	}
  }
}


# Add vehicle for brand name
POST http://localhost:9090/graphql
Content-Type: application/json

{
  "query": "mutation addVehicleForBrandName($brandName: String!, $vehicle: VehicleNoBrandNameInput!){  addVehicleForBrandName(brandName: $brandName, vehicle: $vehicle) {      id    modelCode    color     someDerivedField    brand {          country        name    managerName    } } }",
  "variables": {
  	"brandName": "BMW",
  	"vehicle": {
  		"modelCode": "5Series",
    	"color": "white"
  	}
  }
}

###

##### List vehicles
POST http://localhost:9090/graphql
Content-Type: application/json

{
  "query": "query vehicles($count: Int!) {  vehicles(count: $count) {      id    modelCode    someDerivedField    brand {          country     managerName     currency      } } }",
  "variables": {
    "count": 200
  }
}

###

# Update vehicle
POST http://localhost:9090/graphql
Content-Type: application/json

{
  "query": "mutation updateVehicle($id: ID!, $vehicle: VehicleInput!){  updateVehicle(id: $id, vehicle: $vehicle) {      id   modelCode   color   someDerivedField      brand {          country          name      managerName}  }}",
  "variables": {
    "id": 1,
    "vehicle": {
	    "modelCode": "A4",
	    "brandId": 1,
	    "color": "green"
    }
  }
}

###





